
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Table, Field, Row } from '../types';

// --- Import Functions ---

export const parseExcel = async (file: File): Promise<Table | null> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                const data = e.target?.result;
                const workbook = XLSX.read(data, { type: 'binary' });
                const firstSheetName = workbook.SheetNames[0];
                const worksheet = workbook.Sheets[firstSheetName];
                const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1 });

                if (jsonData.length < 2) return resolve(null); // Empty or just header

                const headers = jsonData[0] as string[];
                const rowsData = jsonData.slice(1) as any[];

                const newFields: Field[] = headers.map((h, i) => ({
                    id: `f${Date.now()}_${i}`,
                    name: h || `Column ${i + 1}`,
                    type: 'TEXT' // Default to text
                }));

                const newRows: Row[] = rowsData.map((rowArray, i) => {
                    const rowObj: Row = { id: `r${Date.now()}_${i}` };
                    newFields.forEach((field, index) => {
                        rowObj[field.id] = rowArray[index] || '';
                    });
                    return rowObj;
                });

                const newTable: Table = {
                    id: `t${Date.now()}`,
                    name: file.name.replace(/\.[^/.]+$/, ""),
                    fields: newFields,
                    rows: newRows
                };

                resolve(newTable);
            } catch (err) {
                reject(err);
            }
        };
        reader.readAsBinaryString(file);
    });
};

export const parseMarkdown = async (file: File): Promise<Table | null> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                const text = e.target?.result as string;
                const lines = text.split('\n').map(l => l.trim()).filter(l => l);

                // Simple Markdown Table Parser
                // Look for line starting with |
                const tableLines = lines.filter(l => l.startsWith('|'));
                if (tableLines.length < 3) return resolve(null);

                // Header: | Col1 | Col2 |
                const headerLine = tableLines[0];
                const headers = headerLine.split('|').map(c => c.trim()).filter(c => c);

                // Data starts after separator |---|
                const dataLines = tableLines.slice(2);

                const newFields: Field[] = headers.map((h, i) => ({
                    id: `f${Date.now()}_${i}`,
                    name: h,
                    type: 'TEXT'
                }));

                const newRows: Row[] = dataLines.map((line, i) => {
                    const cells = line.split('|').map(c => c.trim()).filter((_, idx, arr) => idx > 0 && idx < arr.length - 1); // Remove first/last empty from split '| text |'
                    const rowObj: Row = { id: `r${Date.now()}_${i}` };
                    // Fallback if split logic varies (simple split)
                    const actualCells = line.split('|').slice(1, -1).map(c => c.trim());

                    newFields.forEach((field, index) => {
                        rowObj[field.id] = actualCells[index] || '';
                    });
                    return rowObj;
                });

                const newTable: Table = {
                    id: `t${Date.now()}`,
                    name: file.name.replace(/\.[^/.]+$/, ""),
                    fields: newFields,
                    rows: newRows
                };

                resolve(newTable);

            } catch (err) {
                reject(err);
            }
        };
        reader.readAsText(file);
    });
};

// --- Export Functions ---

export const exportToPDF = (table: Table) => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text(table.name, 14, 22);
    doc.setFontSize(11);
    doc.text(`Generated by BaseForge AI - ${new Date().toLocaleDateString()}`, 14, 30);

    const tableColumn = table.fields.map(f => f.name);
    const tableRows = table.rows.map(row => {
        return table.fields.map(f => row[f.id]);
    });

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 40,
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [0, 0, 0], textColor: [255, 95, 31], fontStyle: 'bold' }, // Black & Safety Orange
    });

    doc.save(`${table.name}_report.pdf`);
};
